jobs:
  - name: daily prod model runs
    targetName: prod
    schedule:
      type: cron
      entries: ["0 12 * * *"]
    timeout: 30m
    retryOnFailure: true
    steps:
      - name: run models and tests
        command: dbt build 

  - name: refresh specific models nightly
    targetName: prod
    schedule:
      type: cron
      entries: ["0 0 * * *"]
    steps:
      - name: run models
        command: dbt run

  - name: connection-integrated-schedule
    targetName: prod
    schedule:
      type: integrated
      integrations:
        - abject_normative
    steps:
      - name: run models
        command: dbt run

