jobs:
  - name: daily model runs
    targetName: dev
    timeout: 30m
    retryOnFailure: true
    steps:
      - name: run models
        command: dbt run --target prod
      - name: test models 
        command: dbt test -- target prod
  - name: refresh specific models nightly
    steps:
      - name: run models
        command: dbt run --target test
  - name: connection-integrated-schedule
    steps:
      - name: run models
        command: dbt run --target prod

